<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NLTSQL.Ai\NLTSQL.Ai.csproj" />
    <ProjectReference Include="..\..\src\NLTSQL.Semantics\NLTSQL.Semantics.csproj" />
    <ProjectReference Include="..\..\src\NLTSQL.QueryEngine\NLTSQL.QueryEngine.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
