<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NLTSQL.Core\NLTSQL.Core.csproj" />
    <ProjectReference Include="..\NLTSQL.Semantics\NLTSQL.Semantics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

</Project>
