-- Oracle demo data, generated by the same arithmetic as the PostgreSQL seed so the two
-- databases hold comparable (not byte-identical) volumes for cross-dialect testing.

ALTER SESSION SET CURRENT_SCHEMA = nltsql_demo;

INSERT INTO nltsql_demo.kunde (mandant_id, kundennummer, name, land, branche, segment, angelegt_am)
SELECT
    1 + MOD(i, 2),
    'K' || LPAD(TO_CHAR(i), 6, '0'),
    'Kunde ' || i,
    DECODE(MOD(i, 5), 0, 'DE', 1, 'AT', 2, 'CH', 3, 'NL', 'FR'),
    DECODE(MOD(i, 5), 0, 'Maschinenbau', 1, 'Handel', 2, 'Logistik', 3, 'Chemie', 'Automotive'),
    DECODE(MOD(i, 3), 0, 'KMU', 1, 'Mittelstand', 'Konzern'),
    DATE '2019-01-01' + MOD(i * 7, 2000)
FROM (SELECT LEVEL AS i FROM dual CONNECT BY LEVEL <= 400);

INSERT INTO nltsql_demo.produkt (mandant_id, artikelnummer, bezeichnung, produktgruppe, listenpreis, aktiv)
SELECT
    1 + MOD(i, 2),
    'A' || LPAD(TO_CHAR(i), 6, '0'),
    'Artikel ' || i,
    DECODE(MOD(i, 5), 0, 'Antriebstechnik', 1, 'Sensorik', 2, 'Hydraulik', 3, 'Elektronik', 'Zubehoer'),
    ROUND(25 + MOD(i, 400) * 3.75, 2),
    CASE WHEN MOD(i, 11) = 0 THEN 0 ELSE 1 END
FROM (SELECT LEVEL AS i FROM dual CONNECT BY LEVEL <= 120);

INSERT INTO nltsql_demo.auftrag (
    mandant_id, auftragsnummer, kunde_id, bestelldatum, lieferdatum,
    status, vertriebskanal, nettobetrag, rabattbetrag)
SELECT
    k.mandant_id,
    'AU' || LPAD(TO_CHAR(g.i), 8, '0'),
    k.id,
    DATE '2023-01-01' + MOD(g.i * 3, 950),
    CASE WHEN MOD(g.i, 6) IN (2, 3, 4)
         THEN DATE '2023-01-01' + MOD(g.i * 3, 950) + (3 + MOD(g.i, 12)) END,
    DECODE(MOD(g.i, 6), 0, 'offen', 1, 'bestaetigt', 2, 'versendet', 3, 'versendet', 4, 'versendet', 'storniert'),
    DECODE(MOD(g.i, 3), 0, 'online', 1, 'aussendienst', 'partner'),
    ROUND(320 + MOD(g.i, 900) * 7.25, 2),
    ROUND(MOD(g.i, 40) * 4.5, 2)
FROM (SELECT LEVEL AS i FROM dual CONNECT BY LEVEL <= 6000) g
JOIN (SELECT id, mandant_id, ROW_NUMBER() OVER (ORDER BY id) - 1 AS rn FROM nltsql_demo.kunde) k
  ON k.rn = MOD(g.i, 400);

INSERT INTO nltsql_demo.auftragsposition (
    mandant_id, auftrag_id, produkt_id, positionsnummer, menge, einzelpreis, positionsbetrag)
SELECT
    a.mandant_id,
    a.id,
    p.id,
    pos.n,
    1 + MOD(a.id + pos.n, 25),
    p.listenpreis,
    ROUND((1 + MOD(a.id + pos.n, 25)) * p.listenpreis, 2)
FROM nltsql_demo.auftrag a
JOIN (SELECT LEVEL AS n FROM dual CONNECT BY LEVEL <= 4) pos
  ON pos.n <= 1 + MOD(a.id, 4)
JOIN (SELECT id, listenpreis, ROW_NUMBER() OVER (ORDER BY id) - 1 AS rn FROM nltsql_demo.produkt) p
  ON p.rn = MOD(a.id * 7 + pos.n, 120);

COMMIT;
