<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nltsql.Core\Nltsql.Core.csproj" />
    <ProjectReference Include="..\Nltsql.Infrastructure\Nltsql.Infrastructure.csproj" />
  </ItemGroup>

</Project>
